### PR TITLE
Fix query param bug for single-url service worker install

### LINKED ISSUE #973: Installing service worker failed (due to passing of 2 params without using '&' by OneSignal)
### How can we help?

I've added the OneSignal service worker on my site accessible from https://syllabuzz.in/_functions/OneSignalSDKWorkerjs
It has an HTTP header to register in the root directory. And OneSignal knows where to look for it. (image below)
image

Earlier this used to work fine but now OneSignal calls the SW script by passing 2 parameters without using '&'.
https://www.syllabuzz.in/_functions/OneSignalSDKWorkerjs?appId=1ed59dfe-493a-40a9-b5b9-a07ed0f532a2?sdkVersion=151514
This makes the page blank and it doesn't load. And I see an error in the console.
image

The script does have a valid MIME type. It's just the 2 params without '&' which cause the issue.
Earlier only one parameter (appID) was passed, which used to work.

Also, the SW script loads when the last param is passed with '&' instead of '?'.
https://www.syllabuzz.in/_functions/OneSignalSDKWorkerjs?appId=1ed59dfe-493a-40a9-b5b9-a07ed0f532a2&sdkVersion=151514

Any suggestions on how do I fix it? Or OneSignal needs to update how it calls the SW script?
Thanks.

### PR DESCRIPTION
**Pull request by rgomezp**
To separate query params, we should be using `&` and not `?`

Fixes #973

- - -
This change is [Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Website-SDK/981)

### CODE REVIEW

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Website-SDK/981#-:-NLb7a6Z0obge5a1n-qe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp)

**Comment by tuberelevant2** [comment]
Hi! When will this issue be resolved? I'm unable to use OneSignal on my site.

**Review by pratyooshbhatia — COMMENTED** [review]
:lgtm:

> @pratyooshbhatia reviewed 3 files and all commit messages, and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/981#-:-OrQa1De6wVbDquiBjQK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved.

**Review by pratyooshbhatia — COMMENTED** [review]
:lgtm:

> @pratyooshbhatia made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/981#-:-Ota446mA4Cafa4Usno2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved.

**Pull request merged**
