### PR TITLE
Remove ServiceWorker Page Control Requirement

### PR DESCRIPTION
**Pull request by jkasten2**
# Description
## 1 Line Summary
Remove ServiceWorker page control requirement.

### Summary
**_This is a quick 2 minute summary, recommend also seeing the [full spike work here](https://github.com/OneSignal/OneSignal-Website-SDK/issues/615) after reading this summary._**
Removes the requirement of the service worker scope to be at or higher than the page you are viewing. (AKA the ServiceWorker has control of the page)

* _You may have known you could[ already customize the path and scope of the OneSignal ServiceWorker ](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#custom-code-setup---service-worker-customizations) before this but it still meant the user has to be on a page in it's scope._

APIs that assumed only one ServiceWorker is on a domain has been replaced with `navigator.serviceWorker.getRegistration(scope)`.

* Examples; `navigator.serviceWorker.controller` & `navigator.serviceWorker.ready`

Dev Sandbox has been updated to a non-root scope to demonstrate these changes work.

#### What this means
* No need to merge ServiceWorker files per the  ["Integrating Multiple Service Workers"](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#section-integrating-multiple-service-workers) guide to support the following.
* Compatibility with AMP, when using your own domain (AKA not Google proxied)
* Compatibility with PWA
* And any other service worker that requires page control

#### What is PR does NOT do
* Does not change the default scope
  * This is intended so there is no breaking changes to those who have already setup this SDK. A change in the default will be done in the future.
* Does not allow more than one OneSignal ServiceWorker per domain. Example `en/push/onesignal` and `es/push/onesignal`
     - This is because the same index.db, sessionStorage, and others would be shared.

### [Full Details](https://github.com/OneSignal/OneSignal-Website-SDK/issues/615)
See issue #615 for the full research done before this PR was created.

# Systems Affected
* [x] WebSDK
* [ ] Backend
* [ ] Dashboard

# Validation
## Tests
Tests have been updated and pass. Need to evaluate changes if we some new tests.

### Checklist
* [X] All the automated tests pass or I explained why that is not possible
* [X] I have personally tested this on my machine or explained why that is not possible
  * Tested Edge(Chromium), and Firefox on Windows 10.
  * Tested Chrome and Safari on macOS
  * Tested both HTTP and HTTPS sites
  * Tested ServiceWorker upgrading versions
  * Tested on_focus and on_session works
  * Tested notification open focuses an existing tab when it should
  * Tested with and without another SW at the root scope along with OneSignal being sub-scoped.
* [X] I have included test coverage for these changes or explained why they are not needed
   - Added `ServiceWorkerUtilHelper` tests
   - Added `throws` to a new mock for service worker APIs that require page control which we should never use again.

**Programming Checklist**
Interfaces:

* [x] Don't use default export
* [x] New interfaces are in model files

Functions:

* [x] Don't use default export
* [x] All function signatures have return types
* [x] Helpers should not access any data but rather be given the data to operate on.

Typescript:

* [x] No Typescript warnings
* [x] Avoid silencing null/undefined warnings with the exclamation point

Other:

* [x] Iteration: refrain from using `elem of array` syntax. Prefer `forEach` or use `map`
* [x] Avoid using global OneSignal accessor for `context` if possible. Instead, we can pass it to function/constructor so that we don't call `OneSignal.context`
   - Some new `OneSignal.context` were introduced into this PR as injection of the `serviceWorkerManager` would have required a number of changes. I recommend instead we come up with a strategy on removing this in another unrelated PR.

### Page to SW Message race condition 
I had a concern about how soon you can send a message to a ServiceWorker after registering it. It seems right away as long as you `await` on `navigator.serviceWorker.getRegistration()` and check all 3 possible state the worker can be in.

#### Proof of this behavior:
**Page:**
```javascript
async function testThis() {
  await navigator.serviceWorker.register("pwa-sw.js");
  var getReg = await navigator.serviceWorker.getRegistration();
  var curSw = getReg.installing || getReg.waiting || getReg.active;
  curSw.postMessage("[Page -> SW] Hello from page!");
  console.log("getReg.installing: " + getReg.installing + " waiting: " + getReg.waiting + " active: " + getReg.active);
}
testThis();
```
**pwa-sw.js:**
```javascript
self.addEventListener('message', function(event) {
    console.log("[SW Context] Got Messsage: ", event);
});
```
**Results:**
```
02:26:22.019 getReg.installing: [object ServiceWorker] waiting: null active: null debugger eval code:9:18
02:26:22.019 [SW Context] Got Messsage:  [object ExtendableMessageEvent] pwa-sw.js:3:13
02:26:22.020 undefined
```
image
Confirmed this on Edge(Chromium) 88.0.705.63 , Firefox 85.0.2, and Safari 13.1.2.

### Subscribe to push race condition
I had a concern about how soon you can subscribe for push after the service worker is registered. As long as you `await` on `navigator.serviceWorker.getRegistration()` this isn't an issue in my testing.
**Page:**
```javascript
/**
 * urlBase64ToUint8Array
 * 
 * @param {string} base64String a public vavid key
 */
function urlBase64ToUint8Array(base64String) {
    var padding = '='.repeat((4 - base64String.length % 4) % 4);
    var base64 = (base64String + padding)
        .replace(/\-/g, '+')
        .replace(/_/g, '/');

    var rawData = window.atob(base64);
    var outputArray = new Uint8Array(rawData.length);

    for (var i = 0; i < rawData.length; ++i) {
        outputArray[i] = rawData.charCodeAt(i);
    }
    return outputArray;
}

async function testThis() {
  await navigator.serviceWorker.register("pwa-sw.js");
  var getReg = await navigator.serviceWorker.getRegistration();  
  var pushOptions = {
    userVisibleOnly: true,
    applicationServerKey: urlBase64ToUint8Array(
        'BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuBkr3qBUYIHBQFLXYp5Nksh8U'
      )
  };
  var pushSub = await getReg.pushManager.subscribe(pushOptions);
  console.log("pushSub: " + JSON.stringify(pushSub.toJSON()));
}
testThis();
```

**Results:**
```
00:00:35.533
/**
 * urlBase64ToUint8Array
 * 
 * @param {string} base64String a public vavid key
 */…
00:00:35.570
Promise { "pending" }
​
<state>: "fulfilled"
​
<value>: undefined

00:00:35.696 pushSub: {"endpoint":"https://updates.push.services.mozilla.com/wpush/v2/gAAAAABgL…wt29fu6xANwYULvF8u26_o5kNRL18yaTtkUjUkLZBDyguWSaJJWHsr95J87E","keys":{"auth":"HoHFMcrC6byl7BxPpXNF0A","p256dh":"BFT49CnizDrRFdzqQRHSmdRUjKDWvwKco6jzzmKOTFgfbSRjEuBokz0CZxgE6J0bwKnxSCapQKqIp7W7a3tJP0o"}}
```

Confirmed this on Edge(Chromium) 88.0.705.63 and Firefox 85.0.2. 

## Checklist
* [x] I have included screenshots/recordings of the intended results or explained why they are not needed

- - -
## Related Tickets
* Issue #615
* PR #389
---

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745)

### CODE REVIEW

**Review by itrush — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745)* status: 15 of 23 files reviewed, 2 unresolved discussions (waiting on @itrush, @jkasten2, and @rgomezp)

___
*[src/helpers/SubscriptionHelper.ts, line 165 at r3](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTmERL74jWzp5-8OAYV:-MTmERL86mRAYlyyA_mI:b-eb97rd) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/42bec5fe11aad0f65d48711a89ffcbbe94cdec8d/src/helpers/SubscriptionHelper.ts#L165)):*
> ```
> OneSignal.context.serviceWorkerManager
> ```
possibly replace with function argument to keep helper clean of dependencies
___
*[src/helpers/page/ServiceWorkerUtilHelper.ts, line 20 at r3](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTmIZz7EtWeC_DHuxnl:-MTmIZz7EtWeC_DHuxnm:br48aep) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/42bec5fe11aad0f65d48711a89ffcbbe94cdec8d/src/helpers/page/ServiceWorkerUtilHelper.ts#L20)):*
> ```
> throw new Error("Could not find an available ServiceWorker instance!");
> ```
just be careful about this error, it may break people's sites

**Review by itrush — COMMENTED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745)* status: all files reviewed, 2 unresolved discussions (waiting on @jkasten2 and @rgomezp)

**Review by jkasten2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745)* status: 18 of 30 files reviewed, 2 unresolved discussions (waiting on @itrush and @rgomezp)

___
*[src/helpers/SubscriptionHelper.ts, line 165 at r3](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTmERL74jWzp5-8OAYV:-MTsBvMYBcw9U1Td-SXt:b-ctzbg8) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/42bec5fe11aad0f65d48711a89ffcbbe94cdec8d/src/helpers/SubscriptionHelper.ts#L165)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

> ```
> OneSignal.context.serviceWorkerManager
> ```
possibly replace with function argument to keep helper clean of dependencies
</blockquote></details>

I move the access to `OneSignal.context.serviceWorkerManager` down one level to `SubscriptionHelper.getRawPushSubscription` to make things a bit more separated. However the call stack for this goes through MainHelper.createDeviceRecord which is also static and has 7 entry points. This helper layering isn't the best design and adding a 3 param to each seems like a side step.

This points to a larger issues of using state through statics instead of creating instance where we can do dependency injection.
___
*[src/helpers/page/ServiceWorkerUtilHelper.ts, line 20 at r3](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTmIZz7EtWeC_DHuxnl:-MTsBbvSDq5y15rQTrDt:b4ea5xb) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/42bec5fe11aad0f65d48711a89ffcbbe94cdec8d/src/helpers/page/ServiceWorkerUtilHelper.ts#L20)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

> ```
> throw new Error("Could not find an available ServiceWorker instance!");
> ```
just be careful about this error, it may break people's sites
</blockquote></details>

Fixed! Turned this into a warning. On the consuming end added a null check.

**Review by itrush — APPROVED** [review]
> Reviewed 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745)* status: all files reviewed, 6 unresolved discussions (waiting on @jkasten2 and @rgomezp)

___
*[src/helpers/SubscriptionHelper.ts, line 165 at r3](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTmERL74jWzp5-8OAYV:-MTvZtcjEWYxII4JBwBx:b-28nkkq) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/42bec5fe11aad0f65d48711a89ffcbbe94cdec8d/src/helpers/SubscriptionHelper.ts#L165)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I move the access to `OneSignal.context.serviceWorkerManager` down one level to `SubscriptionHelper.getRawPushSubscription` to make things a bit more separated. However the call stack for this goes through MainHelper.createDeviceRecord which is also static and has 7 entry points. This helper layering isn't the best design and adding a 3 param to each seems like a side step.

This points to a larger issues of using state through statics instead of creating instance where we can do dependency injection.
</blockquote></details>

yeah, it's asking for a nice refactor :) but if it's too involved, let's keep it simple for now
___
*[src/managers/ServiceWorkerManager.ts, line 89 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_FVk-6ndFGyM0zyv:-MTv_FVl6ezf2Htz-DWe:b-q1u23r) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/src/managers/ServiceWorkerManager.ts#L89)):*
> ```
> ····
> ```
nit: extra spaces
___
*[test/support/mocks/service-workers/models/MockServiceWorkerContainer.ts, line 7 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_Roc8SfDJ5zFE2kp:-MTv_Roc8SfDJ5zFE2kq:bq8tas4) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/support/mocks/service-workers/models/MockServiceWorkerContainer.ts#L7)):*
> ```
> ·
> ```
nit: trailing whitespace
___
*[test/support/mocks/service-workers/models/MockServiceWorkerContainerWithAPIBan.ts, line 13 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_WX76XFYgvewhsDZ:-MTv_WX76XFYgvewhsD_:bv83np1) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/support/mocks/service-workers/models/MockServiceWorkerContainerWithAPIBan.ts#L13)):*
> ```
> ··
> ```
nit: trailing spaces
___
*[test/support/mocks/service-workers/models/MockServiceWorkerContainerWithAPIBan.ts, line 46 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_gZo1gJxuc0Rq1Gp:-MTv_gZo1gJxuc0Rq1Gq:b-obfocn) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/support/mocks/service-workers/models/MockServiceWorkerContainerWithAPIBan.ts#L46)):*
> ```
> }
> ```
nit: empty line at the end of the file
___
*[test/unit/helpers/page/ServiceWorkerUtilHelper.ts, line 34 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_sx2-X8iC7ou6H86:-MTv_sx2-X8iC7ou6H87:b-yl75sr) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/unit/helpers/page/ServiceWorkerUtilHelper.ts#L34)):*
> ```XML
> });
> 
> // See test/unit/manager/ServiceWorkerManager.ts for other tests that cover this class
> ```

nit: new line at the end of the file
___
*[test/unit/managers/ServiceWorkerManager.ts, line 187 at r3](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTva2bgEfsM8vM70VxQ:-MTva2bgEfsM8vM70VxR:bwkbokw) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/42bec5fe11aad0f65d48711a89ffcbbe94cdec8d/test/unit/managers/ServiceWorkerManager.ts#L187)):*
> ```
> navigator.serviceWorker.controller
> ```
just to double-check: if someone writes it like this in tests, it would throw too?
___
*[test/unit/meta/mockPushManager.ts, line 57 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTvde1sDps4ANsJzPfe:-MTvde1t7o1lnW5VHC88:b-izta75) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/unit/meta/mockPushManager.ts#L57)):*
> ```
> subscribedSubscription
> ```
subscribed subscription, buttery butter :upside_down_face:

**Review by jkasten2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745)* status: 25 of 30 files reviewed, 6 unresolved discussions (waiting on @itrush and @rgomezp)

___
*[src/helpers/SubscriptionHelper.ts, line 165 at r3](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTmERL74jWzp5-8OAYV:-MTvmJ4o6BS_jZLNaSmx:b-ucfknh) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/42bec5fe11aad0f65d48711a89ffcbbe94cdec8d/src/helpers/SubscriptionHelper.ts#L165)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

yeah, it's asking for a nice refactor :) but if it's too involved, let's keep it simple for now
</blockquote></details>

Thanks!
___
*[src/managers/ServiceWorkerManager.ts, line 89 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_FVk-6ndFGyM0zyv:-MTvmX7XAkCuuR5RX_05:bt2vr0y) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/src/managers/ServiceWorkerManager.ts#L89)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

> ```
> ····
> ```
nit: extra spaces
</blockquote></details>

Fixed!
___
*[test/support/mocks/service-workers/models/MockServiceWorkerContainer.ts, line 7 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_Roc8SfDJ5zFE2kp:-MTvmY_pEBn9U3i5iVYr:bt2vr0y) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/support/mocks/service-workers/models/MockServiceWorkerContainer.ts#L7)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

> ```
> ·
> ```
nit: trailing whitespace
</blockquote></details>

Fixed!
___
*[test/support/mocks/service-workers/models/MockServiceWorkerContainerWithAPIBan.ts, line 13 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_WX76XFYgvewhsDZ:-MTvmZyX3ZUHHPIIH52l:bt2vr0y) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/support/mocks/service-workers/models/MockServiceWorkerContainerWithAPIBan.ts#L13)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

> ```
> ··
> ```
nit: trailing spaces
</blockquote></details>

Fixed!
___
*[test/support/mocks/service-workers/models/MockServiceWorkerContainerWithAPIBan.ts, line 46 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_gZo1gJxuc0Rq1Gp:-MTvm_YHBFvWXgFmzPMO:bt2vr0y) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/support/mocks/service-workers/models/MockServiceWorkerContainerWithAPIBan.ts#L46)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

> ```
> }
> ```
nit: empty line at the end of the file
</blockquote></details>

Fixed!
___
*[test/unit/helpers/page/ServiceWorkerUtilHelper.ts, line 34 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTv_sx2-X8iC7ou6H86:-MTvmaAR3lab7sG4_Ysc:bt2vr0y) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/unit/helpers/page/ServiceWorkerUtilHelper.ts#L34)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

nit: new line at the end of the file
</blockquote></details>

Fixed!
___
*[test/unit/managers/ServiceWorkerManager.ts, line 187 at r3](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTva2bgEfsM8vM70VxQ:-MTvmajo4bcL-Un7zCaw:bz8gfon) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/42bec5fe11aad0f65d48711a89ffcbbe94cdec8d/test/unit/managers/ServiceWorkerManager.ts#L187)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

> ```
> navigator.serviceWorker.controller
> ```
just to double-check: if someone writes it like this in tests, it would throw too?
</blockquote></details>

Yes! Also will throw if someone adds this to something in src /and it runs in any test.
___
*[test/unit/meta/mockPushManager.ts, line 57 at r4](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/745#-MTvde1sDps4ANsJzPfe:-MTvqSol1mehB88crAYm:bwmzi2a) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/46fca9acb49432c619341fc423dec750570d89e9/test/unit/meta/mockPushManager.ts#L57)):*
<details><summary><i>Previously, itrush (Iryna Trush) wrote…</i></summary><blockquote>

> ```
> subscribedSubscription
> ```
subscribed subscription, buttery butter :upside_down_face: 
</blockquote></details>

haha, just making sure someone doesn't think it is I can't believe it's not butter! :laughing:

Anyway I picked a better name.

**Comment by jkasten2** [comment]
> ### Subscribe to push race condition
> I had a concern about how soon you can subscribe for push after the service worker is registered. As long as you `await` on `navigator.serviceWorker.getRegistration()` this isn't an issue in my testing.
> **Page:**
> ```javascript
> /**
>  * urlBase64ToUint8Array
>  * 
>  * @param {string} base64String a public vavid key
>  */
> function urlBase64ToUint8Array(base64String) {
>     var padding = '='.repeat((4 - base64String.length % 4) % 4);
>     var base64 = (base64String + padding)
>         .replace(/\-/g, '+')
>         .replace(/_/g, '/');
> 
>     var rawData = window.atob(base64);
>     var outputArray = new Uint8Array(rawData.length);
> 
>     for (var i = 0; i < rawData.length; ++i) {
>         outputArray[i] = rawData.charCodeAt(i);
>     }
>     return outputArray;
> }
> 
> async function testThis() {
>   await navigator.serviceWorker.register("pwa-sw.js");
>   var getReg = await navigator.serviceWorker.getRegistration();  
>   var pushOptions = {
>     userVisibleOnly: true,
>     applicationServerKey: urlBase64ToUint8Array(
>         'BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuBkr3qBUYIHBQFLXYp5Nksh8U'
>       )
>   };
>   var pushSub = await getReg.pushManager.subscribe(pushOptions);
>   console.log("pushSub: " + JSON.stringify(pushSub.toJSON()));
> }
> testThis();
> ```

It turned out this wasn't always true. If another service worker is registered already under a scope of the newly registered one you may get the first one. Example first service worker scope could be `/` and the 2nd one `/my-scope` you may sometimes get the service worker at `/` and something the one at `/my-scope`.

This part of the logic from this PR was corrected in PR #1136

**Pull request merged**
