### PR TITLE
Add email support

### PR DESCRIPTION
**Pull request by jasonpang**
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/316)

### CODE REVIEW

**Comment by jkasten2** [comment]
Reviewed 29 of 30 files at r1.
Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/OneSignal.ts, line 172 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-website-sdk/316#-L4mZVMdmejOj8H6CjTn:-L4mZVMdmejOj8H6CjTo:bv4lj7r) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/7c80574752c9178c493e469dd5793f4711d5d25f/src/OneSignal.ts#L172)):*
> ```XML
>     }
> 
>     if (
> ```

Code style feedback. The comments, newlines, and indentations make this very complex if statement readable but feel it could be better. May store some of these into variables before adding them to the if. Or create a new function and return early with a number of smaller if statements. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-website-sdk/316)*

**Comment by jasonpang** [comment]
*[src/OneSignal.ts, line 172 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-website-sdk/316#-L4mZVMdmejOj8H6CjTn:-L4mmSGTv9hyBZbTugSq:bnd30ca) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/7c80574752c9178c493e469dd5793f4711d5d25f/src/OneSignal.ts#L172)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Code style feedback. The comments, newlines, and indentations make this very complex if statement readable but feel it could be better. May store some of these into variables before adding them to the if. Or create a new function and return early with a number of smaller if statements. 
</blockquote></details>

Cleaned it up with the latest commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-website-sdk/316)*

**Comment by jkasten2** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-website-sdk/316)*

**Comment by jasonpang** [comment]
Changing branch to `feature/email` that has a rebase.

**Pull request closed without merging**
