### PR TITLE
Randomize Confirmed Delivery to 25 second max delay

### PR DESCRIPTION
**Pull request by rgomezp**
# Description
Add 25 randomized delay to Confirmed Deliveries

## Details
Aim is to lighten load on backend systems

# Systems Affected
   - [x] WebSDK
   - [x] Backend
   - [ ] Dashboard

# Validation
### Info
Tests pass

### Checklist
   - [x] All the automated tests pass or I explained why that is not possible
   - [x] I have personally tested this on my machine or explained why that is not possible
   - [x] I have included test coverage for these changes or explained why they are not needed
      - Small change, complicated to test

**Programming Checklist**
Interfaces:
   - [x] Don't use default export
   - [x] New interfaces are in model files

Functions:
   - [x] Don't use default export
   - [x] All function signatures have return types
   - [x] Helpers should not access any data but rather be given the data to operate on.

Typescript:
   - [x] No Typescript warnings
   - [x] Avoid silencing null/undefined warnings with the exclamation point

Other:
   - [x] Iteration: refrain from using `elem of array` syntax. Prefer `forEach` or use `map`
   - [x] Avoid using global OneSignal accessor for `context` if possible. Instead, we can pass it to function/constructor so that we don't call `OneSignal.context`

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/841)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
Can we manually test on Firefox & Chrome with a static 25 second wait to ensure the request still goes through and a "This site has been updated in the background" notification does not show? 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/841#-:-Md3Ufw7CfFnD_-GnZqy:bcpwv7m)* status: all files reviewed, 1 unresolved discussion (waiting on @rgomezp)

___
*[src/service-worker/ServiceWorker.ts, line 372 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/841#-Md3V1jL3P4MC9FAWRMr:-Md3V1jL3P4MC9FAWRMs:b-df6dzg) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/a0a9ff9eefc401355ccc4dec22fc10e59e29c1c2/src/service-worker/ServiceWorker.ts#L372)):*
> ```XML
>     })`, Utils.getConsoleStyle('code'));
> 
>     await awaitableTimeout(Math.floor(Math.random() * MAX_CONFIRMED_DELIVERY_DELAY));
> ```

I believe our `awaitableTimeout` takes millisecond, not seconds so we need to times by 1_000 here.

**Review by jkasten2 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/841)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @rgomezp)

**Comment by rgomezp** [comment]
> Can we manually test on Firefox & Chrome with a static 25 second wait to ensure the request still goes through and a "This site has been updated in the background" notification does not show?
> 
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/841#-:-Md3Ufw7CfFnD_-GnZqy:bcpwv7m)_ status: all files reviewed, 1 unresolved discussion (waiting on @rgomezp)
> 
> _[src/service-worker/ServiceWorker.ts, line 372 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/841#-Md3V1jL3P4MC9FAWRMr:-Md3V1jL3P4MC9FAWRMs:b-df6dzg) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/a0a9ff9eefc401355ccc4dec22fc10e59e29c1c2/src/service-worker/ServiceWorker.ts#L372)):_
> 
> > ```
> >     })`, Utils.getConsoleStyle('code'));
> > 
> >     await awaitableTimeout(Math.floor(Math.random() * MAX_CONFIRMED_DELIVERY_DELAY));
> > ```
> 
> I believe our `awaitableTimeout` takes millisecond, not seconds so we need to times by 1_000 here.

Tested, and there's no warnings

**Review by jkasten2 — CHANGES_REQUESTED** [review]
4 tests are failing
https://travis-ci.com/github/OneSignal/OneSignal-Website-SDK/builds/230922257#L808-L815

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/841#-:-MdJ1XAaBWtm-nCngjke:bqqka3m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp)

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/841)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp)

**Pull request merged**
