### PR TITLE
Feat/web prompts

### PR DESCRIPTION
**Pull request by rgomezp**
# Description
## 1 Line Summary
Feature: WebPrompts / Channel Capture Slidedowns

## Details
# Systems Affected
* [x] WebSDK
* [ ] Backend
* [ ] Dashboard

# Validation
### Checklist
* [x] All the automated tests pass or I explained why that is not possible
* [x] I have personally tested this on my machine or explained why that is not possible
* [x] I have included test coverage for these changes or explained why they are not needed
   - **Note:** validation test for SMS is not included since validation is done by 3rd party library ITI

**Programming Checklist**
Interfaces:
* [x] Don't use default export
* [x] New interfaces are in model files

Functions:
* [x] Don't use default export
* [x] All function signatures have return types
* [x] Helpers should not access any data but rather be given the data to operate on.

Typescript:
* [x] No Typescript warnings
* [x] Avoid silencing null/undefined warnings with the exclamation point

Other:

* [x] Iteration: refrain from using `elem of array` syntax. Prefer `forEach` or use `map`
* [x] Avoid using global OneSignal accessor for `context` if possible. Instead, we can pass it to function/constructor so that we don't call `OneSignal.context`

### Checklist
* [x] I have included screenshots/recordings of the intended results or explained why they are not needed

https://user-images.githubusercontent.com/11739227/114101275-19766e00-988b-11eb-90fa-5812d05f0add.mov

https://user-images.githubusercontent.com/11739227/114101279-1bd8c800-988b-11eb-984a-f6f678dc3273.mov

https://user-images.githubusercontent.com/11739227/114101282-1da28b80-988b-11eb-9f45-560506829b45.mov

- - -
## Related Tickets
- - -
## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 44 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777)* status: all files reviewed, 10 unresolved discussions (waiting on @rgomezp)

___
*[package.json, line 91 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY73Cq59PewEJXk8_5L:-MY73Cq59PewEJXk8_5M:btg2bq7) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/package.json#L91)):*
> ```JSON
>     "tslint": "^5.10.0",
>     "tslint-eslint-rules": "^5.2.0",
>     "typescript": "^4.1.2",
> ```

This line is a duplicate. `"typescript": "^4.1.2",` is already there 4 lines above this one.
___
*[src/OneSignal.ts, line 965 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY79k0SDHp5ACMz3Mpw:-MY79k0SDHp5ACMz3Mpx:b-g1hd7n) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/OneSignal.ts#L965)):*
> ```XML
>   static eventHelper = EventHelper;
>   static initHelper = InitHelper;
>   static testHelper = DismissHelper;
> ```

Class and file name was fixed to be `TestHelper` but this variable is still called "testHelper" and should be updated. Also it looks like it might no longer be used, so may just be able to delete this line as a fix.
___
*[src/errors/ChannelCaptureError.ts, line 29 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7T80f5LhzYFyc8sg1:-MY7T80f5LhzYFyc8sg2:b-8kh0xd) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/errors/ChannelCaptureError.ts#L29)):*
> ```XML
>     }
> 
>   super(errorMessage);
> ```

nit, indetention off on this line down.
___
*[src/managers/PromptsManager.ts, line 203 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7XJT_ByS1CCiaJt0m:-MY7XJT_ByS1CCiaJt0n:bsrme5t) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/managers/PromptsManager.ts#L203)):*
> ```XML
>    * @param  {AutoPromptOptions} options - passed in via another internal function or top level OneSignal slidedown func
>    */
>   public async internalShowParticularSlidedown(typeToPullFromConfig: DelayedPromptType, options?: AutoPromptOptions)
> ```

From reading the logic in this function it seems like `options.slidedownPromptOptions` overrides `typeToPullFromConfig` if present. If that is the case could you make that more clear here?
___
*[src/managers/slidedownManager/SlidedownManager.ts, line 118 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7YhH61f2E-gtF3ORw:-MY7YhH61f2E-gtF3ORx:b-390lt7) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/managers/slidedownManager/SlidedownManager.ts#L118)):*
> ```XML
>       isSmsEmpty = ChannelCaptureContainer.isSmsInputFieldEmpty();
> 
>       /** */
> ```

Remove empty comment
___
*[src/managers/slidedownManager/SlidedownManager.ts, line 197 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7Z9Hq-3xjEDqRYtYR:-MY7Z9Hq-3xjEDqRYtYS:blynl3h) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/managers/slidedownManager/SlidedownManager.ts#L197)):*
> ```XML
>     }
> 
>     if (slidedown) {
> ```

This function is really long and doing a number of different things. One suggestion that comes to mind is moving this UI related logic into its own function.
___
*[src/slidedown/ChannelCaptureContainer.ts, line 205 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7tH504bIsIDp2eZ-G:-MY7tH504bIsIDp2eZ-H:b-i53tcb) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/slidedown/ChannelCaptureContainer.ts#L205)):*
> ```XML
> 
>   private async loadPhoneLibraryScripts(): Promise<void> {
>     const script1 = document.createElement("script");
> ```

I don't see anything preventing adding the InternationalTelephoneInput more than once to the page if the prompt is display multiple times. We should add a check for this.
___
*[src/slidedown/ChannelCaptureContainer.ts, line 261 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7tr615HdzA8wF7_nV:-MY7tr615HdzA8wF7_nW:bjm81qy) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/slidedown/ChannelCaptureContainer.ts#L261)):*
> ```XML
> 
>   static isSmsInputFieldEmpty(): boolean {
>     const onesignalSmsInput = document.querySelector(`#${CHANNEL_CAPTURE_CONTAINER_CSS_IDS.onesignalSmsInput}`);
> ```

Email has a helper for `ChannelCaptureContainer.getValueFromEmailInput()` but SMS does not have a similarly named one?
___
*[test/unit/prompts/TaggingContainer.ts, line 15 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7wRPgBoFi5d4ht2rq:-MY7wRPgBoFi5d4ht2rr:b-g9rlft) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/test/unit/prompts/TaggingContainer.ts#L15)):*
> ```XML
>   (global as any).BrowserUserAgent = BrowserUserAgent;
>   (global as any).location = new URL("https://localhost:4001");
>   const userConfig =  TestEnvironment.getFakeMergedConfig({});
> ```

It looks like this `await` was removed by mistake.
___
*[test/unit/prompts/SlidedownPrompting/SlidedownPrompting.ts, line 277 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7wj5S10QrNWbHw_2X:-MY7wj5S10QrNWbHw_2Y:b-xou96z) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/test/unit/prompts/SlidedownPrompting/SlidedownPrompting.ts#L277)):*
> ```XML
> });
> 
> test.todo(`multiple slidedowns of same type with different options are shown with respective config`);
> ```

There is a test that is still TODO

**Review by rgomezp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777)* status: all files reviewed, 9 unresolved discussions (waiting on @jkasten2 and @rgomezp)

___
*[package.json, line 91 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY73Cq59PewEJXk8_5L:-MYBU_gt3C2PeU_WjNAu:b-896fix) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/package.json#L91)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This line is a duplicate. `"typescript": "^4.1.2",` is already there 4 lines above this one.
</blockquote></details>

Done.
___
*[src/OneSignal.ts, line 965 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY79k0SDHp5ACMz3Mpw:-MYBUwZCBmBEYNwa1wbg:b-896fix) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/OneSignal.ts#L965)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Class and file name was fixed to be `TestHelper` but this variable is still called "testHelper" and should be updated. Also it looks like it might no longer be used, so may just be able to delete this line as a fix.
</blockquote></details>

Done.
___
*[src/managers/PromptsManager.ts, line 203 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7XJT_ByS1CCiaJt0m:-MYBVrJSDVd3euLAvitX:blk94bb) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/managers/PromptsManager.ts#L203)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

From reading the logic in this function it seems like `options.slidedownPromptOptions` overrides `typeToPullFromConfig` if present. If that is the case could you make that more clear here?
</blockquote></details>

this is explained in the @param definition in the JSDoc comment. but I'll add `If present, `options.slidedownPromptOptions` overrides `typeToPullFromConfig``
___
*[src/managers/slidedownManager/SlidedownManager.ts, line 118 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7YhH61f2E-gtF3ORw:-MYBW894AN1XJysAzRjW:b-2uvhfe) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/managers/slidedownManager/SlidedownManager.ts#L118)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove empty comment
</blockquote></details>

comment is there on purpose to separate from the above comment
___
*[src/slidedown/ChannelCaptureContainer.ts, line 205 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7tH504bIsIDp2eZ-G:-MYBoefU0zUdHobsEX0o:b6zrrk4) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/slidedown/ChannelCaptureContainer.ts#L205)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I don't see anything preventing adding the InternationalTelephoneInput more than once to the page if the prompt is display multiple times. We should add a check for this.
</blockquote></details>

Good catch!
___
*[src/slidedown/ChannelCaptureContainer.ts, line 261 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7tr615HdzA8wF7_nV:-MYBoztd9u0m23RWUr6w:b-ftum36) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/slidedown/ChannelCaptureContainer.ts#L261)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Email has a helper for `ChannelCaptureContainer.getValueFromEmailInput()` but SMS does not have a similarly named one?
</blockquote></details>

Good catch. We do have one, I just forgot to invoke it here
___
*[test/unit/prompts/TaggingContainer.ts, line 15 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7wRPgBoFi5d4ht2rq:-MYBpBuZBKs3to_Fc2er:b-ocgbai) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/test/unit/prompts/TaggingContainer.ts#L15)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

It looks like this `await` was removed by mistake.
</blockquote></details>

it was on purpose. the function is synchronous
___
*[test/unit/prompts/SlidedownPrompting/SlidedownPrompting.ts, line 277 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7wj5S10QrNWbHw_2X:-MYC3Ulz29Cy4WQkDkeL:b-896fix) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/test/unit/prompts/SlidedownPrompting/SlidedownPrompting.ts#L277)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

There is a test that is still TODO
</blockquote></details>

Done.

**Review by jkasten2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777)* status: all files reviewed, 6 unresolved discussions (waiting on @jkasten2 and @rgomezp)

___
*[src/managers/PromptsManager.ts, line 203 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7XJT_ByS1CCiaJt0m:-MYC70uc300uPl1KiVsi:b-fgol7n) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/managers/PromptsManager.ts#L203)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

this is explained in the @param definition in the JSDoc comment. but I'll add `If present, `options.slidedownPromptOptions` overrides `typeToPullFromConfig``
</blockquote></details>

ah you are right, I think was looking something saying "override" but your comment explains it.
___
*[src/managers/slidedownManager/SlidedownManager.ts, line 118 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7YhH61f2E-gtF3ORw:-MYC7IVnBa3orqEkLk8A:b-q8ilnv) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/managers/slidedownManager/SlidedownManager.ts#L118)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

comment is there on purpose to separate from the above comment
</blockquote></details>

gotcha
___
*[test/unit/prompts/TaggingContainer.ts, line 15 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7wRPgBoFi5d4ht2rq:-MYC7bUP4KNbs_dcMILU:b-qj4s1b) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/test/unit/prompts/TaggingContainer.ts#L15)):*
<details><summary><i>Previously, rgomezp (Rodrigo Gomez Palacio) wrote…</i></summary><blockquote>

it was on purpose. the function is synchronous
</blockquote></details>

ah, you are correct.

**Review by rgomezp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777)* status: 34 of 44 files reviewed, 6 unresolved discussions (waiting on @jkasten2)

___
*[src/managers/slidedownManager/SlidedownManager.ts, line 197 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7Z9Hq-3xjEDqRYtYR:-MYCa7cx7RfJuSA1oYwG:b-896fix) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/src/managers/slidedownManager/SlidedownManager.ts#L197)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This function is really long and doing a number of different things. One suggestion that comes to mind is moving this UI related logic into its own function.
</blockquote></details>

Done.
___
*[test/unit/prompts/TaggingContainer.ts, line 15 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-MY7wRPgBoFi5d4ht2rq:-MYCVO704GvfhYK-RmWl:b-896fix) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/c5eeea7ba6ad9f9fe971025203eb263653284218/test/unit/prompts/TaggingContainer.ts#L15)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

ah, you are correct.
</blockquote></details>

Done.

**Comment by rgomezp** [comment]
BEFORE MERGING, AUTOSQUASH
---

**Review by jkasten2 — APPROVED** [review]
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp)

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/777#-:-MYDKZ5y8MbzP70ft1W_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp)

**Pull request merged**
